version: "3"

services:
  env1:
    build:
      context: .
      dockerfile: Dockerfile

    image: my_env:latest
    container_name: env1
    command: ["/bin/bash", "-c", "tail -f /dev/null"]
    tty: true
    stdin_open: true
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./tmp/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml
